import os
from dotenv import load_dotenv
from openai import OpenAI
from langchain_core.messages import AIMessage
from ..state import AgentState

# Load your API key from local .env
load_dotenv("deep_research_agent/.env")

# Initialize the OpenAI official client
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

def report_node(state: AgentState):
    # Extract the summary generated by analyze_node
    summary = state["messages"][-1].content

    # Prompt for generating a well-structured research report
    prompt = f"""
    Turn this summary into a structured research report using the following format:

    # Title
    ## Executive Summary
    ## Key Findings
    ## Detailed Insights
    ## Recommendations
    ## Sources

    Summary:
    {summary}
    """

    # Call GPT-4o-mini to generate the final report
    completion = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0
    )

    # Correct extraction for OpenAI Python SDK v1.x
    report_text = completion.choices[0].message.content

    # Wrap the final report as an AIMessage
    report_msg = AIMessage(content=report_text)

    # Add the final report to the message flow
    return {"messages": state["messages"] + [report_msg]}
